#! /bin/bash
# ensure_git directory clone_addreess
# will make sure that directory exists and upto date otherwise clone it
DIR=$1
ADDR=$2

#this currently isn't particuarly sophisticated you could imagine 
if [ -d $DIR/.git ]; then
  git pull;
else
  git clone $ADDR $DIR;
fi;
echo "ensured $DIR"
