#!/bin/bash

[ -n "$SSH_CLIENT" ] && SESSION_TYPE="remote"

if [[ $SESSION_TYPE == "remote" ]]; then
# -c in bsd/osx -q1 in debian
  cat | nc -q1 localhost 2224
else
  cat | xclip -selection clipboard
fi
