#! /bin/bash
#create required directories if they doen't exist
curdir=$(pwd)

mkdir -p ~/.marks

which brew 
if [ $? -eq 0 ]; then
  #this machine has brew running
  echo "We are going to brew install some things"
  brew update
  for pkg in `cat requirements/brew.txt | tr '\n' ' '`; do
      if brew list -1 | grep -q "^${pkg}\$"; then
        :
      else
          brew install $pkg
      fi
  done
fi 

which apt-get
if [ $? -eq 0 ]; then
  #this machine has apt-get
  echo "We are going to sudo apt-get install some things"
  sudo apt-get update
  sudo apt-get -y install `cat requirements/apt-get.txt | tr '\n' ' '`
fi 

which pip
if [ $? -eq 0 ]; then
  #this machine has pip
  echo "we are going to pip install some things"
  pip install -r requirements/pip.txt
fi


#run the rest of the install script
python install.py
if [ $? -eq 0 ]; then
    #Run all scripts in install_scripts
    cd install_scripts
    for file in *.sh; do
      ./$file
      cd $curdir/install_scripts
    done
  else
    echo "Main Install Script failed"
    exit
fi

if [ -f ~/.ssh/id_rsa.pub ]; then
  :
else 
  #this machine doesn't have a key
  echo "We are going to generate a ssh keys"
  ssh-keygen
fi 

#test if you your git stuffs is configured correctly
ssh -T git@github.com
if [ $? -eq 0 ]; then
  #add code to upgrade your https://remote repo to git@github. So we don't have to worry about adding in our username and what not
  :
else
  echo "you need to copy your ssh key to github to be able to use ssh keys to login"
fi
