#! /bin/bash
#create required directories if they doen't exist
curdir=$(pwd)
mkdir -p ~/scripts
mkdir -p ~/.marks

#ensure gat is up to date
if [ -d ~/.gat ]; then
  cd ~/.gat
  git pull
else
  git clone https://github.com/zingales/gat.git ~/.gat
fi
cd ~/.gat
cp ex_gat_script ~/scripts/gat

cd $curdir

echo $curdir

python install.py

./git_config.sh
