
#! /bin/bash
#autogenerated install script

NAME=gat
DIR=~/.gat
FORCE=true
INST=".le_installed"

if [ -d $DIR ]; then
  cd $DIR
  if [[ -a $INST && "$FORCE" = false ]] ; then
      echo "$NAME already installed"
  else
      cp ex_gat_script ~/scripts/gat;
      touch $INST
      echo "$NAME (re)installed"
  fi;
else
  echo "$NAME's $DIR not found"
fi;
