#this file should be called .bashrc

#ignore hisotry repeats
export HISTCONTROL=ignoredups:ignorespace

#append to bash history if termianl quits
shopt -s histappend

#allows color in the terminal
export CLICOLOR=1

#import my file with all bash functions
source ~/.bash_functions

#put whatever name you want for your machine before the : by writing it in .name
if [ -f ~/.name ]; then 
  name=$(cat ~/.name)
else
  name=$(echo '')
fi

#Modifies the prompt
# 0=black, 1=red, 2=green, 3 = yellow, 4 = blue, 5 = purple, 6= light blue, anything else = white
green=$(tput setaf 2)
red=$(tput setaf 1)
reset=$(tput sgr0)
PS1='\[$green\][$name:\w]\$\[$reset\] '

#Add what git branch your on to your prompt
#PS1='\[$green\][$name:\w]\[$red\]$(git-branch-prompt)\[$green\]\$\[$reset\] '

#Mac ls colors
#export LSCOLORS=GxFxCxDxBxegedabagaced

#Linux ls colors + more
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'


# add my own scripts folder to path after everything else
PATH="${PATH}:~/scripts"
export PATH

#adds mark jump command to terminal
source ~/.marksrc
